import React, { FunctionComponent, useState } from 'react';
import {
  Card,
  Grid,
} from '@material-ui/core';
import Button from '../components/Button';
import Layout from "../components/Layout";
import Link from "../components/Link";
import Accordion from '@material-ui/core/Accordion';
import AccordionSummary from '@material-ui/core/AccordionSummary';
import AccordionDetails from '@material-ui/core/AccordionDetails';
import Typography from '@material-ui/core/Typography';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';

import Faq from '../assets/images/others/faq.gif';

import CheckIcon from '@material-ui/icons/Check';

const Help = () => {
  return (
    <Layout>
      <section className=''>
        <Grid container className='datasection'>
          <Grid item md={12} className="p-15">
            <h2>
              You control your data
            </h2>
            <p>
              In short, TruPaid does not share your personally identifiable information with advertisers, merchants, or others unless you tell us. We aim to earn your trust.</p>
          </Grid>
        </Grid>
      </section>

      <Grid>
        <header id="hero2" className="main-footer">
          <div className='row align-items-center text-left pb-5'>
            <Grid container>
              <Grid item md={2} className=""></Grid>
              <Grid item md={8} className="">

                <div class="ql-editor"><h2>Privacy Policy</h2><p><br />
                </p><p><span >TruPaid takes your information privacy and security extremely seriously.</span></p><p><br />
                  </p><p><span >Well Paid operates and is only successful by earning your trust. To earn that trust, we carefully guard and restrict the usage of your data. In plain terms, that means we DO NOT send your personal information or information that can directly be tagged to you to anyone without your explicit permission. Further, we use advanced 256-bit encryption to encrypt any personal or financial information shared with us. In short, your information security and privacy is built into TruPaid’s core.</span></p><p><br />
                  </p><p><span >If you have any questions or concerns regarding our Privacy Policy or practices, please contact us at help@gettrupaid.com and we would be happy to help.</span></p><p><br />
                  </p><p><span >More detailed information on what information is stored, how it is safe-guarded, and where it is needed below.</span></p><p><br />
                  </p><h3><span >What personal information do we collect and why do we need it?</span></h3><p><span >Here are the types of information we gather.</span></p><p><br />
                  </p><h3><span >Personal Information:</span></h3><p><span >When you create TruPaid account, we ask you to provide your name, email address, password, and phone number (encrypted). We require these fields in order to use TruPaid so that we can contact you about your account, help you connect with others, and can access data from other devices. Roommates or those you elect to share bills with will be able to add you using your email address or phone number. Your phone number and email address are not displayed when connecting to others, however, we do send a message on their behalf to facilitate the connection. Email and phone numbers also enable an extra layer of security for your account. You can make changes to this information from your Account Settings page or by emailing us at help@gettrupaid.com.&nbsp;</span></p><p><br />
                  </p><h3><span >Other Personal Information:</span></h3><p><span >We may also be required to verify your identity to comply with certain obligations and laws. In such an event, we will ask you to provide us with information like your name, date of birth, your social security number, images of your government-issued identification, and mailing address. With the exception of your name and mailing address (which we will use and store in accordance with this Privacy Policy), we will not store the other information you provide in such an event after it has been used for these purposes.</span></p><p><br />
                  </p><h3><span >Third-Party Financial Institution Login: </span></h3><p><span >On setup, we prompt you to connect to third-party financial institutions or third-party payments providers with which you have a legally binding customer relationship (each, a “Third-Party Financial Institution”). To enable us to access your financial data with Third-Party Financial Institutions, you will need to provide (as applicable): the name of the Third-Party Financial Institution, the username or email associated with that institution, the password for your financial account, and other similar information. We collect this information to establish a connection with your financial accounts and gain access to information and data we need to provide you with the services you request, including your bank account and routing number with that institution. </span></p><p><br />
                  </p><h3><span >We do not store your bank account and routing number in our systems.</span></h3><p><br />
                  </p><h3><span >Third-Party Financial Institution Information:</span></h3><p><span >When you authorize us to access information from your financial accounts with Third-Party Financial Institutions, we collect information about those accounts, including the balance of those accounts, what type of institution is holding the account, and what type of account is involved (i.e., checking or savings and credit or depository). We also collect information about the transactions that have taken place with that financial account, including, but not limited to, the amount of the transaction, the recipient of the transaction, the location of the transaction, the merchant category code, and the time of the transaction. This information is to provide your unified overview of transaction history, categorize expenses, track recurring expenses and help you keep track of upcoming expenses.</span></p><p><br />
                  </p><h3><span >Shared Expenses and Bill Splitting:</span></h3><p><span >If you enable other users to access pieces of information, such as the amount of a joint bill or names of others connected in the group, then we will publish the information with the intended recipient(s) while others outside of the group will not be able to see this information. TruPaid offers the ability to add or delete users from a group, both by the group leader and for the groups you elect to join, but specified bill details and information published while someone is part of a group is considered available for all parties within the group. You are solely responsible which contacts and information that you share with recipients on the platform.&nbsp;</span></p><p><br />
                  </p><h3><span >Account Signup with Google and Apple:</span></h3><p><span >Google and Apple accounts are available to connect to your TruPaid account to simplify the signup experience. If you authorize TruPaid to use your Google Account to login, your name, contact information such as an email address, and other basic account details (profile picture, age, gender, birthday) may be shared with TruPaid at your discretion. Sharing this data is not required to start a TruPaid account. These details will be stored by TruPaid and will generally be treated as if you had manually provided that data to TruPaid under this privacy policy and encrypted. Information from TruPaid regarding your financial transactions, balances, connected accounts or any personally identifying information will not be shared back with Google or Apple unless directly used for purposes of conducting a transaction for which TruPaid is used as a funding instrument in either a Google Pay or Apple Pay wallet.&nbsp;</span></p><p><br />
                  </p><h3><span >Google or Apple Contacts:</span></h3><p><span >If you give TruPaid access to your contacts as part of using our service, this contact data may be used in a limited way: to send TruPaid invitations on your behalf to others to split bills (to individuals specifically authorized by you; not in bulk), to locate others who already use TruPaid, to recommend others to invite to TruPaid, and to improve our services (for example, to identify common email spelling errors in user support).&nbsp;</span></p><p><br />
                  </p><h3><span >Updates Shared to TruPaid:</span></h3><p><span >Information that you provide to TruPaid to use the service in stored in order to better serve you. This information can include shared expenses, payments, communications with others, group or bill names, categorization of expenses, amounts, reminders, receipt images, and memos. TruPaid will store your changes to your proposed budget to better serve you in later tracking expenses and alerts.</span></p><p><br />
                  </p><h3><span >Public Communications on the Blog:</span></h3><p><span >We offer the ability to communicate via a blog, message boards, or similar public forums where you can communicate with us or other users. Any information that you submit or post to these blogs or other forums could be viewed by other viewers or may otherwise be publicly available. Therefore, we recommend to not include personal information in public forums. If you choose to post personal information, other viewers may use this information to send you unsolicited messages. We are not responsible for the personal information you choose to submit in these blogs and other forums, so please be careful about what you disclose and do not post any information that you expect to keep private. If you would like to request removal of your information from our blogs or other forums, please contact us at help@gettrupaid.com.</span></p><p><br />
                  </p><h3><span >Publicly Available Information:</span></h3><p><span >In addition to the above data, we may use publicly available information about your name, email address, phone number, or other demographic data to help you during support, to address fraud or security concerns, or to personalize your experience, including by providing ads or offers. For instance, if you have a public avatar stored on a service such as Gravatar associated with your email, we may automatically populate your user avatar on TruPaid. We may also collect information about you that we may receive from other sources or from our offline interactions with you to, among other things, enable us to verify, update information contained in our records, and to better customize the Service for you.</span></p><p><br />
                  </p><h3><span >Site Information and Cookies:</span></h3><p><span >We and our partners may use various technologies to collect and store information when you visit our Site. This technology may include the use of cookies, IP addresses, timestamps, or similar technology. We use these cookies and similar technology through Google Analytics to better your experience with our Site. Google utilizes the data collected from our website, through cookies and similar technology, to track and examine the use of the Site, to prepare reports on these activities and share them with us. We use these cookies and the Google Analytics information to improve the delivery and performance of our Site by understanding how you use our site, detecting and defending against fraud, and better presenting advertisement or services.&nbsp;</span></p><p><br />
                  </p><p><span >To provide certain services like data sync across devices or data backup, we store the information provided by the user on our servers, however we delete all this information when user request for account deletion.</span></p><p><br />
                  </p><p><span >Our Services may change over time and we may introduce new features that may collect new or different types of information</span></p><p><br />
                  </p><h3><span >How do we use your information?</span></h3><p><br />
                  </p><p><span >We may use the information we collect from you in the following ways:</span></p><p><br />
                  </p><ul><li><span >To personalize or customize your experience and services, and to improve the overall quality of TruPaid services.</span></li><li><span >To pre-fill forms and fields for your convenience.&nbsp;</span></li><li><span >To allow others to search and find you.</span></li><li><span >To improve our website and application in order to better serve you.</span></li><li><span >To allow us to better service you in responding to your customer service requests.</span></li><li><span >To follow up application bug or crash investigation or to develop new features and services.</span></li><li><span >To communicate with you about our services and to give you offers for the products and services that we think may be of use to you.</span></li><li><span >To resolve questions you may have about our services and to follow up with you about your experience.</span></li><li><span >To better understand our services and how we may improve them.</span></li><li><span >To facilitate transactions, billing, or support bill split services.</span></li><li><span >To protect the site and secure your data.</span></li><li><span >In addition to the above, we may disclose information with third-party vendors who are assisting us with the operation, maintenance, or security of our site. These include the following:</span></li></ul><p><br />
                  </p><h3><span >Astra Finance: </span></h3><p><span >Astra Finance is our account linking facilitator to enable connectivity to Plaid, Dwolla, and other financial service providers.</span></p><p><br />
                  </p><h3><span >Plaid:</span></h3><p><span >As part of providing Well Paid services concerning your financial accounts, we work with a partner, Plaid Technologies, Inc. (“Plaid”), who is authorized to access financial accounts by their partner banks and financial institutions. We use Plaid to gather your data from financial institutions. By using our service, you grant Plaid and us the right, power, and authority to act on your behalf to access and transmit your personal and financial information from the relevant financial institution. You agree to your personal and financial information being transferred, stored, and processed by Plaid in accordance with the Plaid Privacy Policy (https://plaid.com/legal). Plaid receives this information and establishes a connection to those financial accounts. Once the connection is established, we delete the financial account information from our system. We give Plaid the following information about your financial accounts that you provided during account setup:</span></p><p><br />
                  </p><ul><li><span >Name of the financial institution</span></li><li><span >Your username</span></li><li><span >Your email address</span></li><li><span >Password for that financial account</span></li></ul><p><br />
                  </p><h3><span >Dwolla:</span></h3><p><span >As indicated in our Terms of Service, we also work with Dwolla to provide an account for your use through the site. You agree to your personal and financial information being transferred to Dwolla, and being stored and processed by Dwolla in accordance with the Dwolla Terms of Service and the Dwolla Privacy Policy. Please refer to those documents for more complete information about how Dwolla collects, uses, and discloses information about you.</span></p><p><br />
                  </p><h3><span >Google Analytics:</span></h3><p><span >As indicated above, we also provide information regarding your use of our Site or App, or clicks on links to other sites on our Site, to Google Analytics. Though the information we provide can be used to understand how you use our Site, the information cannot be used to identify you.</span></p><p><br />
                  </p><p><span >We may also share personal or financial information with others if we have a good-faith belief that access, use, preservation, or disclosure of the information is reasonably necessary to:</span></p><p><br />
                  </p><ol><li><span >Meet any applicable law, regulation, legal process or enforceable governmental request</span></li><li><span >Enforce applicable Terms of Service, including the investigation of potential violations</span></li><li><span >Detect, prevent, or otherwise address fraud, security or technical issues</span></li><li><span >Protect against harm to the rights, property, or safety of Astra, our users, or the public as required or permitted by law</span></li></ol><p><br />
                  </p><p><span >We may provide access to your information to third-party vendors who may be assisting us with the operation, maintenance, or security of our Site.</span></p><p><br />
                  </p><h3><span >Essential Service Providers:</span></h3><p><span >We also share information with essential third-party service providers as necessary to provide the Site and the services to you. For example, we use Amazon Web Services (AWS) as a cloud server provider, and as such we necessarily share information with AWS. Information shared with such essential service providers is strictly limited to the purposes of providing the Site and the services to you.</span></p><p><br />
                  </p><h3><span >Your choices</span></h3><p><span >You may decline to submit Personally Identifiable Information when registering for our services, in which case we may not be able to provide services to you. If you do not agree with our Privacy Policy, please delete your account, uninstall the application and discontinue use of the our services, your continued usage of the our Application/Services will signify your acceptance of our Privacy Policy.</span></p><p><br />
                  </p><p><span >If you are not satisfied with our services and security and privacy aspect of your data, you may request for deleting the account from account page of the mobile app.</span></p><p><br />
                  </p><h3><span >How do we secure your information?</span></h3><p><span >We at TruPaid use our own product and take your information security very seriously. We know that your trust in our service depends on this. We therefore take the following security measures to protect and secure your information:</span></p><p><br />
                  </p><p><span >We simply do not save your account and routing number when your accounts are created and connected to Plaid. We use encryption on all sensitive personal data. No encryption can ever perfect, but we take your security and have elected to secure data with strong 256-bit encryption.</span></p><p><br />
                  </p><p><span >Data from app or website to our backend servers is transferred over HTTPS which is also and separately encrypted using SSL.</span></p><p><br />
                  </p><p><span >Access of backend services use secure authenticated tokens.</span></p><p><br />
                  </p><h3><span >We also ask a bit from you:</span></h3><p><span >PLEASE keep your passwords safe and not written down or in areas that can be easily retrieved by others.</span></p><p><br />
                  </p><p><span >PLEASE let us know if your password may have been compromised so that we can reset it to something new with you.</span></p><p><br />
                  </p><p><span >PLEASE do not give out your password to anyone outside of logging into the Well Paid site. We will NEVER call, text, or email you to ask for you password. If there is something suspicious with your account we will verify your identity with other means. For more information about phishing, visit the Federal Trade Commission's website at https://www.ftc.gov.</span></p><p><br />
                  </p><p><span >PLEASE let your bank or financial institutions know if a transaction or activity in your individual accounts looks suspicious.&nbsp;</span></p><p><br />
                  </p><h3><span >Third-party disclosure:</span></h3><p><span >We do not sell, rent, or lease any of your information to third parties except as described above with intention of supporting your experience on Well Paid.</span></p><p><br />
                  </p><h3><span >Third-party links:</span></h3><p><span >Occasionally, at our discretion, we may include or offer third-party products or services or their advertisement on our website or app. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites.&nbsp;</span></p><p><br />
                  </p><p><span >Merchants may be able to post links in the community, blog, Home Services, Financial Services, or other open forum components of TruPaid. These links will also direct away from Well Paid and are not governed by TruPaid. Therefore these independent third-parties will also have independent privacy policies. We strongly encourage all our users to understand what information these third party pages collect about them and how it is used.</span></p><p><br />
                  </p><h3><span >COPPA (Children Online Privacy Protection Act):</span></h3><p><span >TruPaid services are intended for and directed to adults. Our services are not directed to minors and we do not knowingly collect personal information from minors.</span></p><p><br />
                  </p><h3><span >Liability:</span></h3><p><span >Notwithstanding anything to the contrary in this Policy or any other terms of service, Company’s aggregate liability hereunder shall be limited to not more than amount you paid us to use the Services and shall not extend to any indirect or remote damages whatsoever, including but not limited to special, incidental, consequential, or punitive damages or loss of profits</span></p><p><br />
                  </p><h3><span >Amendments to Privacy Policy:</span></h3><p><span >We have the right to amend this Privacy Policy at any time, without prior notice to each user. Any changes we may make to our Privacy Policy in the future will be posted here. Where appropriate, we will notify you or seek your consent. Please check back frequently to see any updates or changes to our Privacy Policy.</span></p><p><br />
                  </p><h3><span >Contact info:</span></h3><p><span >We attempt to provide you with accurate information about your financial accounts. To do so, we need accurate information from you about yourself and those accounts. If you find that information we have about you is outdated, missing, or incorrect, we would ask that you notify us at help@gettrupaid.com of these errors so that they can be addressed. We may ask you to verify your identity before we act on any request to change your information. We may also reject requests that are unreasonably repetitive, require extraordinary or disproportionate technical effort or cost, risk the privacy or security of others, or would be extremely impractical.</span></p><p><br />
                  </p><p><span >Last Updated: June 17, 2021</span></p></div>
              </Grid>

              <Grid item md={2} className=""></Grid>
            </Grid>
          </div>
        </header>
      </Grid>

    </Layout>
  );
};

export default Help;
