import React, { FunctionComponent, useState } from 'react';
import {
  Card,
  Grid,
} from '@material-ui/core';
import Button from '../components/Button';
import Layout from "../components/Layout";
import Link from "../components/Link";
import Accordion from '@material-ui/core/Accordion';
import AccordionSummary from '@material-ui/core/AccordionSummary';
import AccordionDetails from '@material-ui/core/AccordionDetails';
import Typography from '@material-ui/core/Typography';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';

import Faq from '../assets/images/others/faq.gif';

import CheckIcon from '@material-ui/icons/Check';

const Help = () => {
  return (
    <Layout>
      <section className=''>
        <Grid container className='datasection'>
          <Grid item md={12} className="p-15">
            <h2>
              Terms of service
            </h2>
            <p>
              Learn about TruPaid's bank grade security, how we operate, and house rules.</p>
          </Grid>
        </Grid>
      </section>

      <Grid>
        <header id="hero2" className="main-footer">
          <div className='row align-items-center text-left pb-5'>
            <Grid container>
              <Grid item md={2} className=""></Grid>
              <Grid item md={8} className="">
                <div classname="ql-editor">
                  <h2>User Agreement:</h2>
                  <p><br />
                  </p>
                  <p>The following terms of service are a legal agreement (the “Agreement”) between you (“you”, “your”, or “user”) and TruPaid Inc., its subsidiaries, affiliates, agents and assigns (“TruPaid”, “we”, “us”, “service”, or “our”) which governs the use of TruPaid’s platform including its mobile application (“Mobile App”) and web application, gettrupaid.com, as well other products and services offered, operated or made available on the TruPaid platform. You agree to comply with all of the terms and conditions in this user agreement. By accepting electronically (for example, clicking “I Agree”), installing, accessing or using the Services, you agree to be bound by the terms and conditions of this Agreement. The terms include an agreement to resolve disputes by arbitration on an individual basis.</p>
                  <p><br />
                  </p>

                  <h3>Using TruPaid Platform &amp; Services:</h3>

                  <p>To create a user account, you must be a resident of the United States or one of its territories, be at least 18 years old or the age of majority in your state of residence and use a cellular/wireless telephone number that you own.You may not use any of TruPaid’s Services and you may not accept this Agreement if you are not legally authorized to accept and be bound by these terms or are not at least 18 years of age and, in any event, of a legal age to form a binding contract with TruPaid.</p><p><br />
                  </p><h3>Effective June 17, 2021 to present</h3><p><br />
                  </p><h3>Consent to Electronic Signature and Communication:</h3><p>By creating an User Account, you explicitly consent to receive all notices and information via emails, push notifications, text message, and other similar means. For the avoidance of doubt, this consent applies to all communications that we may otherwise be required to send or provide to you in paper form or by mail. TruPaid nevertheless reserves the right to communicate with you in paper form or by mail.</p><p><br />
                  </p><p>You may opt out of receiving certain types of notices (such as marketing or promotional notices) by following the opt-out or unsubscribe instructions included with those notices or, in the event you cannot locate those instructions, by contacting us at help@gettrupaid.com.</p><p><br />
                  </p><h3>Authorization to Act as Your Agent:</h3><p>Please read the below section CAREFULLY, as it authorizes us (among other things) to act as your agent for purposes of initiating financial transactions, purchase new services, or cancellation of existing services (and the terms for revoking such authorization).</p><p><br />
                  </p><p>Certain Services we provide require us to collect information about you (“Account Info”) from third-party financial institutions or third-party payments providers with which you have a legally binding customer relationship (each, a “Third-Party Financial Institution”). By using the Services, you expressly authorize and direct TruPaid, on your behalf, to electronically retrieve Account Info from Third-Party Financial Institutions. Subject to the terms of our Privacy Policy, TruPaid may work with one or more third-party financial services providers to access and retrieve such Account Info. You authorize us to share your identity, account data and Account Info with third-party financial institutions with which you have accounts for the purposes of supporting your account and activities, including Services, with such third-party financial institutions, and you are responsible for the accuracy and completeness of that data.</p><p><br />
                  </p><p>Please note that we currently only support Third-Party Financial Institutions based in the United States. You will not be able to use the functionality of the Services, including initiating any transfers and executing any other transactions, with respect to any Third-Party Financial Institutions outside of the United States.</p><p><br />
                  </p><p>Certain Services we provide require your authorization in order to initiate ACH transactions between TruPaid and deposit accounts you identify and designate that are held for your benefit by Third-Party Financial Institutions. You agree to authorize TruPaid to initiate ACH credit and/or debit transactions among your accounts with Third-Party Financial Institutions and your accounts with Astra and Dwolla (as detailed below), both in response to your direct request and automatically at set times based on instructions you explicitly provide (e.g., when you establish weekly, monthly, or other periodic rules-based routines or transfers).</p><p><br />
                  </p><p>In order to use the payment and budgeting functionality of our Site, you must open an account with Astra Finance. This account allows our partner, Astra Finance, to facilitate payment instructions on our behalf. You authorize us to share your identity and account data with Astra Finance for the purposes of opening and supporting your Astra Finance account, and you are responsible for the accuracy and completeness of that data. You understand that you will access and manage your Astra Finance account through our application, and Astra Finance account notifications will be sent by us, not Astra Finance . We will provide customer support for your Astra Finance account activity, and can be reached at help@gettrupaid.com.</p><p><br />
                  </p><p>In order to use the payment functionality of our Site, you must open a “Access API” account provided by Dwolla, Inc. (“Dwolla”) and you must accept the Dwolla Terms of Service and Privacy Policy. Any funds held in the Dwolla account are held by Dwolla’s financial institution partners as set out in theDwolla Terms of Service. You authorize us to share your identity and account data with Dwolla for the purposes of opening and supporting your Dwolla account, and you are responsible for the accuracy and completeness of that data. You understand that you will access and manage your Dwolla account through our application, and Dwolla account notifications will be sent by us, not Dwolla. We will provide customer support for your Dwolla account activity, and can be reached at help@gettrupaid.com.</p><p><br />
                  </p><p>When you initiate an ACH transfer between your accounts held with one or more Third-Party Financial Institutions, we will execute two separate transfers. First, we will debit the amount of your requested transfer from the originating account. Second, we will credit the same amount, less any fees charged by the Third-Party Financial Institutions or by us (any fees charged by us are set forth in these Terms of Service), to the recipient account. You are solely responsible for ensuring that you have sufficient funds in the originating account to complete the transfer. If you do not have sufficient funds in your originating account to cover a transaction you initiate through the Services, or in the event of a chargeback, we may take any action we deem necessary and appropriate, including, but not limited to, reversing the credit to the recipient account, if possible, or withdrawing funds from another account held by you to cover the cost of the transaction and any other fees or losses incurred by us as a result of insufficient funds or any chargebacks.</p><p><br />
                  </p><p>You acknowledge and agree that, as consideration for TruPaid providing to you Services that may require us to initiate ACH transactions as described herein, you waive your right to receive prior notice of the amount and date of each debit and credit.</p><p><br />
                  </p><p>You acknowledge and agree that, as consideration for TruPaid providing to you Services that may require us to initiate ACH transactions as described herein, TruPaid will not be liable for any third-party fees that may be incurred as a result of transactions you authorize us to perform on your behalf, including but not limited to third-party fees incurred as a result of maintaining insufficient funds in your accounts with Third-Party Financial Institutions.</p><p><br />
                  </p><p>You acknowledge that the authorizations contained in this section represent your written authorization for ACH transactions, and that these authorizations will remain in full force and effect until you notify us that you wish to revoke this authorization. You acknowledge and agree that TruPaid may require a commercially reasonable prior notice in order to effectuate your revocation, and may require at least three (3) business days prior to any scheduled debit or credit date in order to revoke, cancel, or stop a previously authorized transaction.</p><p><br />
                  </p><p>When you initiate a transaction through the Services, you represent and warrant that any accounts with Third-Party Financial Institutions that you link to TruPaid belong to you, and that you are not attempting to transfer funds from or to an account not in your name.</p><p><br />
                  </p><p>In order to detect money laundering, fraud and other criminal activity, we may impose certain limitations on your User Account and your ability to transfer funds between your accounts with Third-Party Financial Institutions. For example, you may not initiate any transfers or execute any other transactions before your identity is verified as described in these Terms of Service. Additionally, we may impose limits on the amount of funds you can transfer in a single transaction and/or in a given time period (e.g., a day). We will attempt to, although we will have no obligation for failure to, communicate these limits to you via the Site and/or Services. We reserve the right to change applicable limits as we deem necessary in our sole discretion. Finally, if we reasonably suspect that any transaction is fraudulent or otherwise violates these Terms of Service, we reserve the right to cancel or reverse such transaction, even after funds have been debited from your bank account.</p><p><br />
                  </p><h3>Link or Unlink a Payment Method:</h3><p>You can link or unlink certain payment methods such as a debit card, credit card, or a U.S. bank account to your TruPaid account. Please keep your payment method information current (e.g. credit card number and expiration date). If this information changes, we may update it using information and third party sources available to us without any action on your part. If you do not want us to update your card information, you may contact your issuer to request this or remove your payment method from your TruPaid account.</p><p><br />
                  </p><h3>Payments:</h3><p>You can send money to or request money from a TruPaid user using the bill split feature in your TruPaid account. You can also request money from a TruPaid user by splitting certain purchases. They will have to accept any charge request before you are sent money. When you accept a charge request sent by another TruPaid user, you will send them money.</p><p><br />
                  </p><p>We review payments you make at our discretion. When we identify a potentially high-risk payment, we review the transaction more closely before allowing it to proceed. When this happens, we will place a hold on the transaction and notify the payment sender. If we clear the transaction, we will notify you and the receiver of the payment. If we don’t clear the transaction, we will cancel it and return the money to you, unless we are legally required to take other action.</p><p><br />
                  </p><h3>Third Party Financial Institutions &amp; Regulators:</h3><p>You may ask TruPaid to retrieve your information from Third-Party Financial Institutions with which you have an existing customer relationship, where you maintain an account, or where you engage in financial transactions. In addition, TruPaid may engage one or more online services or third-party service providers to access your Account Info on your behalf. TruPaid does not review Account Info for accuracy, legality, or non-infringement. TruPaid is not responsible for the Account Info or for any products or services offered by or on any third-party sites (including those of Third-Party Financial Institutions). Third parties that TruPaid engages may require you to adopt or agree to additional terms of use with respect to their software or services. In the event that any use of third party software or services results in you leaving our Site and entering the site of such a third-party vendor or service provider, you will be subject to the terms of use and the privacy policy of that third-party vendor or service provider. TruPaid strongly suggests that you review such terms carefully before proceeding.</p><p><br />
                  </p><p>In addition, if you access the sites of Third-Party Financial Institutions through the Services, you will be subject to the terms of use and privacy policies for those sites. TruPaid again cautions you to familiarize yourself with the terms of use and privacy policies of your financial institutions before undertaking any such access.</p><p><br />
                  </p><p>Portions of the Site and/or Services offered thereon may be supported by sponsored links from advertisers. The Site may display special offers or opportunities to acquire products or services custom matched to you based on information available to TruPaid through the Site and Services. We may disclose when a particular offer is sponsored or otherwise provided by a third party.</p><p><br />
                  </p><p>The Site may provide links to other sites belonging to TruPaid advertisers, marketing partners, or other third parties. These links are provided to you as a convenience. TruPaid does not endorse, warrant, or guarantee the products or services available through any such links found on the Site (or any other third-party products or services advertised on or linked from our Site), whether or not sponsored. TruPaid is not an agent or broker or otherwise responsible for the activities or policies of any such sites. TruPaid does not guarantee that the terms of any offers, plans, or rewards offered to you through links on the Site are actually the terms that may be offered to you if you pursue the offer or that they are the best terms or lowest rates available in the market. Information associated with any links found on the Site are provided by the third parties, and any such offer is subject to the third parties’ review of your information. TruPaid may receive compensation from third parties which may impact the placement and availability of links found on the Site.</p><p><br />
                  </p><p>If you elect to use or purchase products or services from third parties whose links appear on the Site, you are subject to any applicable terms of use and/or privacy policies they may have in association with their sites.</p><p><br />
                  </p><p>TruPaid shall have no responsibility or liability for any sites, services, products, or other offerings of any third parties beyond TruPaid’s control, including, without limitation, any Third-Party Financial Institutions, any third parties TruPaid engages to access your Account Info, or any third-party advertisers or marketers.</p><p><br />
                  </p><h3>Billing &amp; Paid Subscriptions:</h3><p>By default, access and use of the Services is offered free of charge. However, certain features or services offered through the Services may be offered only to paying customers. If you choose to sign up for a paid User Account or upgrade a free User Account to a paid subscription, you hereby authorize us to charge your designated payment method on a monthly basis until you cancel your paid subscription. If we are unable to charge your designated payment method for the monthly subscription fees, you hereby authorize us to directly withdraw any unpaid balance from your linked accounts with Third-Party Financial Institutions.</p><p><br />
                  </p><h3>Refunds:</h3><p>Except as otherwise expressly provided herein or as otherwise required by applicable law, Payments authorized in connection with certain TruPaid services are non-refundable. We are not responsible for any loss of funds if you give incorrect instructions or if your payment instructions are not given sufficiently in advance to allow for timely delivery of your payment. You represent and warrant that all payments you make comply with applicable law.</p><p><br />
                  </p><h3>Eligibility &amp; Limits:</h3><p>In order to use the TruPaid services, you must have a Checking or Credit Account in good standing with the Bank. As a result, all of the eligibility requirements set forth in these terms must be satisfied in order for you to use the TruPaid Services. If you suspend your TruPaid Account, you will not be able to use TruPaid services on its platform. Similarly, if your TruPaid Account is closed entirely, you will no longer be able to access any of TruPaid services.</p><p><br />
                  </p><p>We may decline to complete or delay a Payment: (i) if we believe it may involve or result in a violation of applicable law or expose us to liability or risk of loss; (ii) if the Payment instructions or authorization are unclear, ambiguous, or incomplete; (iii) if we identify a fraud or security risk involving an individual Payment or the Direct Payments Service; or (iv) as otherwise stated in these terms and conditions. We are not responsible for any losses or damages that may result from our delay or cancellation of a payment or for any failure to notify you of such delay or cancellation, except as otherwise expressly provided under these terms. You agree not to use the TruPaid services in connection with unlawful domestic or international gambling websites or payment processors that support unlawful gambling websites or to purchase illegal goods or services.</p><p><br />
                  </p><h3>Disputes With Businesses:</h3><p>We are not responsible for the delivery, quality, safety, legality or any other aspect of goods or services for which payments are made using any of TruPaid services.</p><p><br />
                  </p><h3>Fees:</h3><p>We may, at our discretion, impose limits on the amount and/or the number of payments you can send and receive. Sending limits apply for all transactions combined in your account. The fees applicable to receiving, withdrawing and sending money can be found on the Fees page. If you use your credit card as the payment method when sending money, you may also be charged a cash-advance fee by your card issuer. In order to manage risk, we may limit the payment methods available when you make a payment. Fees and limits may change from time to time at our sole discretion.</p><p><br />
                  </p><h3>Taxes &amp; Financial Reporting:</h3><p>Our fees do not include any taxes, levies, duties or similar governmental assessments of any nature, including, for example, value-added, sales, use or withholding taxes, that may be assessed by any jurisdiction (collectively, “taxes”). It is your responsibility to determine what, if any, taxes apply to the payments you make or receive, including any business transactions or that are marked as for goods and services, and it is solely your responsibility to assess, collect, report and remit the correct taxes to the appropriate authority. TruPaid is not responsible for determining whether any taxes apply to your transaction, or for calculating, collecting, reporting or remitting taxes arising from any transaction. You acknowledge that we may make certain reports to state and federal tax authorities regarding transactions that we process.</p><p><br />
                  </p><h3>Termination Of Services:</h3><p>You may close your account and terminate your relationship with us without cost, but you will remain liable for all obligations related to your TruPaid account even after the TruPaid account is closed. Any incomplete transactions or transfers must be completed or canceled and you must transfer any money from any personal or business profiles of your TruPaid account before closing it. In certain cases, you may not close your TruPaid account, including:</p><p><br />
                  </p><p>● To evade an investigation.</p><p>● If you have a pending transaction or an open dispute or claim.</p><p>● If you owe amounts to us.</p><p>● If your TruPaid account is subject to a hold, limitation or reserve.</p><p><br />
                  </p><p>If your TruPaid account is closed for any reason, any business profile and any Debit Card affiliated with your account will be canceled.</p><p><br />
                  </p><p>Your access to TruPaid’s platform and services may be terminated at any time, for any reason, at TruPaid Inc. sole discretion. This includes the right to ban any person from the service who uses the TruPaid platform to send spam, unwanted or hostile communications.</p><p><br />
                  </p><h3>Privacy &amp; Data Sharing:</h3><p>When you use or access the Site and/or Services, we may collect certain information about you, including personally identifiable information. We take your privacy and the security of information we collect very seriously. Please read TruPaid’s Privacy Policy carefully for details relating to our collection, use, and disclosure of your information.</p><p><br />
                  </p><h3>Indemnification:</h3><p>You agree to hold Well Paid Inc., its employees, agents, and representatives, as harmless and indemnify Well Paid Inc. from any third party claim arising from or in any way related to your use of the Service, including liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs, and attorney fees, of every kind and nature.</p><p><br />
                  </p><h3>No Warranty:</h3><p>Well Paid Inc. does not represent the Service as error-free, complete, or can be relied upon. THE SERVICE IS PROVIDED 'AS IS' AND 'AS AVAILABLE' WITH NO WARRANTY OF ANY KIND AND YOU ARE USING THE SERVICE AT YOUR OWN RISK. TRUPAID INC DISCLAIMS ANY WARRANTY, IMPLIED OR OTHERWISE, REGARDING THE SERVICE, INCLUDING WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, INCLUDING FOR PREMIUM SERVICES.</p><p><br />
                  </p><h3>Disclaimers:</h3><p>The Services Are Not Intended To Provide Legal, Tax Or Investment/Retirement Planning Advice Or Intended To Serve As Tax Preparation Services. The Services are intended only to assist you in your financial organization and decision-making and are broad in scope. Your personal financial situation is unique, and any information and advice obtained through TruPaid’s platform may not be appropriate for your situation. Accordingly, before making any final decisions or implementing any financial strategy, you should consider obtaining additional information and advice from financial professionals who are fully aware of your individual circumstances.</p><p><br />
                  </p><h3>Insolvency Proceedings:</h3><p>If any proceeding by or against you is commenced under any provision of the United States Bankruptcy Code, as amended, or under any other bankruptcy or insolvency law, we’ll be entitled to recover all reasonable costs or expenses (including reasonable legal fees and expenses) incurred in connection with the enforcement of this agreement.</p><p><br />
                  </p><h3>Changes To Terms:</h3><p>We may modify, suspend, or discontinue any TruPaid services and/or revise these Terms from time to time at our sole discretion without prior notice or liability to you, subject to applicable law. If we are required to provide you notice of any changes to these Terms, we will do so in accordance with the Electronic Communications Agreement. Subject to applicable law, your continued use of the TruPaid platform and services following such notice shall be deemed to be your acceptance of such modified version of these Terms.</p><p><br />
                  </p><h3>Governing Law:</h3><p>TruPaid will be governed by and interpreted in accordance with the laws of the State of Delaware.</p><p><br />
                  </p><h3>Limitation Of Liability:</h3><p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE AND ANY PROGRAM MANAGER, ISSUER, AND DEPOSITORY, OUR AND THEIR AFFILIATES, AND OUR AND THEIR RESPECTIVE EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, AND CONTRACTORS WILL NOT BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS TO OR USE OF TRUPAID PLATFORM &amp; SERVICE OR ANY INFORMATION, PRODUCTS, OR OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE THROUGH ITS PARTNER PAYMENTS SERVICES, INCLUDING, BUT NOT LIMITED TO, ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE. WITHOUT LIMITING THE FOREGOING AND TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN THE EVENT YOU OR ANY OTHER PERSON OR ENTITY IS ENTITLED TO DIRECT DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS, USE, OR INABILITY TO ACCESS OR USE, TRUPAID PLATFORM OR SERVICE OR ANY INFORMATION, PRODUCTS, OR OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE THROUGH THE TRUPAID PLATFORM, THE COLLECTIVE LIABILITY OF TRUPAID INC. AND ANY PROGRAM MANAGER, ISSUER, AND DEPOSITORY, OUR AND THEIR AFFILIATES, AND OUR AND THEIR RESPECTIVE EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, AND CONTRACTORS (REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, OR OTHERWISE) WILL NOT EXCEED $100.</p><p><br />
                  </p><p>IN ADDITION TO AND WITHOUT LIMITING ANY OF THE FOREGOING, WE AND ANY PROGRAM MANAGER, ISSUER, OR DEPOSITORY WILL HAVE NO LIABILITY FOR ANY FAILURE OR DELAY RESULTING FROM ANY CONDITION BEYOND OUR REASONABLE CONTROL, INCLUDING, WITHOUT LIMITATION, ACTS OF GOD, ACTS OF TERRORISM, LABOR CONDITIONS, POWER FAILURES, INTERNET DISTURBANCES, OR ANY SERVICES OR SYSTEMS CONTROLLED BY THIRD PARTIES.</p><p><br />
                  </p><p>THE LIMITATIONS IN THIS SECTION DO NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p><p><br />
                  </p><h3>Privacy &amp; Security:</h3><p>In order to provide the services to you we collect some of your Personal Information. We describe our collection and use of personal information in our Privacy Policy. Please review this policy. You must agree to the processing of your data as laid out in that policy in order to use our services. You agree that TruPaid Inc. may disclose personal information provided to us, including content of emails, messages, and data entered into the site, if required by law or government request such as a warrant, or as specified in the Privacy Policy. You must be 18 years or older to use this service. You are responsible for preventing unauthorized access to your account.</p><p><br />
                  </p><p>California Consumer Privacy Act. For the purposes of the California Consumer Privacy Act (“CCPA”), TruPaid shall be considered a Business and/or Third Party, as applicable. Where TruPaid acts as a Third Party, you represent, warrant and covenant that all Personal Information provided or otherwise made available to TruPaid is done so in compliance with applicable law, and that you have provided all necessary and appropriate notices and opt-outs, and otherwise have all necessary and appropriate rights, to enable TruPaid to (i) share any and all Personal Information you provided with any TruPaid company, including TruPaid Inc., its subsidiaries, affiliates, agents and assigns, and (ii) use any such Personal Information in connection with any and all TruPaid Inc. and its subsidiaries, internal operations and functions, including, but not limited to, improving TruPaid Inc., its subsidiaries, affiliates, agents and assigns products and/or services, operational analytics and reporting, internal financial reporting and analysis, audit functions and archival purposes. Notwithstanding the foregoing, the parties agree that the sharing of Personal Information between TruPaid Inc., its subsidiaries, affiliates, agents and assigns does not constitute a “sale” of such Personal Information under the CCPA. Capitalized terms in this paragraph have the meanings given those terms under the CCPA.</p><p><br />
                  </p><h3>Arbitration:</h3><p>For any dispute you may have with TruPaid, you agree to first contact us at help@gettrupaid.com and to work with us in good faith to resolve the dispute informally. In the event we are not able to resolve your dispute within sixty (60) days after you brought it to our attention, you and TruPaid mutually agree to resolve any claim, dispute, or controversy (excluding claims that qualify for small claims court and claims for equitable relief, as provided below) arising out of or in connection with this Agreement or your access or use of the Site and/or Services (collectively, “Claims”) by binding arbitration by JAMS, under the Optional Expedited Arbitration Procedures then in effect for JAMS, except as provided herein. Information about JAMS, including contact information, can be found at www.jamsadr.com.</p><p><br />
                  </p><p>The arbitrator, and not any federal, state, or local court or agency, will have exclusive authority to resolve any Claims relating to the interpretation, applicability, enforceability or formation of the Arbitration Section in these Terms of Service, including but not limited to any claim that all or any part of this Arbitration Section is void or voidable. The judgment of the arbitrator and the award of the arbitrator is final and binding on you and TruPaid.</p><p><br />
                  </p><p>The arbitration will be conducted in New Hanover, Delaware, unless you and TruPaid agree otherwise. JAMS may require you to pay a fee for the initiation of your case, unless you apply for and obtain a fee waiver from JAMS. The award rendered by the arbitrator may include your costs of arbitration, your reasonable attorney’s fees, and your reasonable costs for expert and other witnesses.</p><p><br />
                  </p><p>All Claims must be brought in YOUR individual capacity, and not as a plaintiff or class member in any purported class action, collective action, private attorney general action or other representative proceeding. This waiver applies to class arbitration, and, unless we agree otherwise, the arbitrator may not consolidate more than one person’s Claims. You agree that, by entering into this Agreement, you and TruPaid are each waiving the right to a trial by jury or to participate in a class action, collective action, private attorney general action, or other representative proceeding of any kind.</p><p><br />
                  </p><p>Nothing in this Arbitration Section will be deemed as preventing you or TruPaid from seeking equitable relief from the courts as necessary and applicable, nor for adjudicating a Claim in small claims court if that Claim qualifies so long as the Claim remains in such court and advanced only on an individual basis, not a class or representative basis.</p><p><br />
                  </p><h3>Severability:</h3><p>If any part of this agreement is held to be invalid or unenforceable, the provision shall be deemed to be superseded by a valid enforceable provision in its place that closely matches the intent of the original agreement, and all other parts of the agreement shall be enforced.&nbsp;</p></div>
              </Grid>

              <Grid item md={2} className=""></Grid>
            </Grid>
          </div>
        </header>
      </Grid>

    </Layout>
  );
};

export default Help;
